/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdr;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NotBilledRatedCDR extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3038071444613574856L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotBilledRatedCDR\",\"namespace\":\"com.cdr\",\"fields\":[{\"name\":\"cdrID\",\"type\":\"int\"},{\"name\":\"MSISDN_A\",\"type\":\"string\"},{\"name\":\"quantityTypeID\",\"type\":\"int\"},{\"name\":\"rate\",\"type\":{\"type\":\"bytes\",\"scale\":3,\"precision\":10,\"logicalType\":\"decimal\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<NotBilledRatedCDR> ENCODER =
      new BinaryMessageEncoder<NotBilledRatedCDR>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotBilledRatedCDR> DECODER =
      new BinaryMessageDecoder<NotBilledRatedCDR>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotBilledRatedCDR> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotBilledRatedCDR> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotBilledRatedCDR> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NotBilledRatedCDR>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotBilledRatedCDR to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotBilledRatedCDR from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotBilledRatedCDR instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotBilledRatedCDR fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int cdrID;
  private java.lang.CharSequence MSISDN_A;
  private int quantityTypeID;
  private java.nio.ByteBuffer rate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotBilledRatedCDR() {}

  /**
   * All-args constructor.
   * @param cdrID The new value for cdrID
   * @param MSISDN_A The new value for MSISDN_A
   * @param quantityTypeID The new value for quantityTypeID
   * @param rate The new value for rate
   */
  public NotBilledRatedCDR(java.lang.Integer cdrID, java.lang.CharSequence MSISDN_A, java.lang.Integer quantityTypeID, java.nio.ByteBuffer rate) {
    this.cdrID = cdrID;
    this.MSISDN_A = MSISDN_A;
    this.quantityTypeID = quantityTypeID;
    this.rate = rate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cdrID;
    case 1: return MSISDN_A;
    case 2: return quantityTypeID;
    case 3: return rate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cdrID = (java.lang.Integer)value$; break;
    case 1: MSISDN_A = (java.lang.CharSequence)value$; break;
    case 2: quantityTypeID = (java.lang.Integer)value$; break;
    case 3: rate = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cdrID' field.
   * @return The value of the 'cdrID' field.
   */
  public int getCdrID() {
    return cdrID;
  }


  /**
   * Sets the value of the 'cdrID' field.
   * @param value the value to set.
   */
  public void setCdrID(int value) {
    this.cdrID = value;
  }

  /**
   * Gets the value of the 'MSISDN_A' field.
   * @return The value of the 'MSISDN_A' field.
   */
  public java.lang.CharSequence getMSISDNA() {
    return MSISDN_A;
  }


  /**
   * Sets the value of the 'MSISDN_A' field.
   * @param value the value to set.
   */
  public void setMSISDNA(java.lang.CharSequence value) {
    this.MSISDN_A = value;
  }

  /**
   * Gets the value of the 'quantityTypeID' field.
   * @return The value of the 'quantityTypeID' field.
   */
  public int getQuantityTypeID() {
    return quantityTypeID;
  }


  /**
   * Sets the value of the 'quantityTypeID' field.
   * @param value the value to set.
   */
  public void setQuantityTypeID(int value) {
    this.quantityTypeID = value;
  }

  /**
   * Gets the value of the 'rate' field.
   * @return The value of the 'rate' field.
   */
  public java.nio.ByteBuffer getRate() {
    return rate;
  }


  /**
   * Sets the value of the 'rate' field.
   * @param value the value to set.
   */
  public void setRate(java.nio.ByteBuffer value) {
    this.rate = value;
  }

  /**
   * Creates a new NotBilledRatedCDR RecordBuilder.
   * @return A new NotBilledRatedCDR RecordBuilder
   */
  public static com.cdr.NotBilledRatedCDR.Builder newBuilder() {
    return new com.cdr.NotBilledRatedCDR.Builder();
  }

  /**
   * Creates a new NotBilledRatedCDR RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotBilledRatedCDR RecordBuilder
   */
  public static com.cdr.NotBilledRatedCDR.Builder newBuilder(com.cdr.NotBilledRatedCDR.Builder other) {
    if (other == null) {
      return new com.cdr.NotBilledRatedCDR.Builder();
    } else {
      return new com.cdr.NotBilledRatedCDR.Builder(other);
    }
  }

  /**
   * Creates a new NotBilledRatedCDR RecordBuilder by copying an existing NotBilledRatedCDR instance.
   * @param other The existing instance to copy.
   * @return A new NotBilledRatedCDR RecordBuilder
   */
  public static com.cdr.NotBilledRatedCDR.Builder newBuilder(com.cdr.NotBilledRatedCDR other) {
    if (other == null) {
      return new com.cdr.NotBilledRatedCDR.Builder();
    } else {
      return new com.cdr.NotBilledRatedCDR.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotBilledRatedCDR instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotBilledRatedCDR>
    implements org.apache.avro.data.RecordBuilder<NotBilledRatedCDR> {

    private int cdrID;
    private java.lang.CharSequence MSISDN_A;
    private int quantityTypeID;
    private java.nio.ByteBuffer rate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cdr.NotBilledRatedCDR.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cdrID)) {
        this.cdrID = data().deepCopy(fields()[0].schema(), other.cdrID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.MSISDN_A)) {
        this.MSISDN_A = data().deepCopy(fields()[1].schema(), other.MSISDN_A);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantityTypeID)) {
        this.quantityTypeID = data().deepCopy(fields()[2].schema(), other.quantityTypeID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.rate)) {
        this.rate = data().deepCopy(fields()[3].schema(), other.rate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing NotBilledRatedCDR instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cdr.NotBilledRatedCDR other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cdrID)) {
        this.cdrID = data().deepCopy(fields()[0].schema(), other.cdrID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MSISDN_A)) {
        this.MSISDN_A = data().deepCopy(fields()[1].schema(), other.MSISDN_A);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantityTypeID)) {
        this.quantityTypeID = data().deepCopy(fields()[2].schema(), other.quantityTypeID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rate)) {
        this.rate = data().deepCopy(fields()[3].schema(), other.rate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'cdrID' field.
      * @return The value.
      */
    public int getCdrID() {
      return cdrID;
    }


    /**
      * Sets the value of the 'cdrID' field.
      * @param value The value of 'cdrID'.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder setCdrID(int value) {
      validate(fields()[0], value);
      this.cdrID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cdrID' field has been set.
      * @return True if the 'cdrID' field has been set, false otherwise.
      */
    public boolean hasCdrID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cdrID' field.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder clearCdrID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'MSISDN_A' field.
      * @return The value.
      */
    public java.lang.CharSequence getMSISDNA() {
      return MSISDN_A;
    }


    /**
      * Sets the value of the 'MSISDN_A' field.
      * @param value The value of 'MSISDN_A'.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder setMSISDNA(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MSISDN_A = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'MSISDN_A' field has been set.
      * @return True if the 'MSISDN_A' field has been set, false otherwise.
      */
    public boolean hasMSISDNA() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'MSISDN_A' field.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder clearMSISDNA() {
      MSISDN_A = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantityTypeID' field.
      * @return The value.
      */
    public int getQuantityTypeID() {
      return quantityTypeID;
    }


    /**
      * Sets the value of the 'quantityTypeID' field.
      * @param value The value of 'quantityTypeID'.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder setQuantityTypeID(int value) {
      validate(fields()[2], value);
      this.quantityTypeID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantityTypeID' field has been set.
      * @return True if the 'quantityTypeID' field has been set, false otherwise.
      */
    public boolean hasQuantityTypeID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantityTypeID' field.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder clearQuantityTypeID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'rate' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getRate() {
      return rate;
    }


    /**
      * Sets the value of the 'rate' field.
      * @param value The value of 'rate'.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder setRate(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.rate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'rate' field has been set.
      * @return True if the 'rate' field has been set, false otherwise.
      */
    public boolean hasRate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'rate' field.
      * @return This builder.
      */
    public com.cdr.NotBilledRatedCDR.Builder clearRate() {
      rate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotBilledRatedCDR build() {
      try {
        NotBilledRatedCDR record = new NotBilledRatedCDR();
        record.cdrID = fieldSetFlags()[0] ? this.cdrID : (java.lang.Integer) defaultValue(fields()[0]);
        record.MSISDN_A = fieldSetFlags()[1] ? this.MSISDN_A : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.quantityTypeID = fieldSetFlags()[2] ? this.quantityTypeID : (java.lang.Integer) defaultValue(fields()[2]);
        record.rate = fieldSetFlags()[3] ? this.rate : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotBilledRatedCDR>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotBilledRatedCDR>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotBilledRatedCDR>
    READER$ = (org.apache.avro.io.DatumReader<NotBilledRatedCDR>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










